#!/system/bin/sh
# DeadB00st
# Copyright (C) 2015 deadman0
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

mount -o remount,rw /
mount -o remount,rw rootfs
mount -o remount,rw /system
busybox mount -o remount,rw /
busybox mount -o remount,rw rootfs
busybox mount -o remount,rw /system

DBLog=/system/etc/DB/Log/DBLogInit.log

Config=/system/etc/DB/Governor.conf

busybox echo "$(date +"%m-%d-%Y %H:%M:%S"): Aplying a Governor tweak.." >> $DBLog

busybox sleep 10


# Ondemand

if [ -e /sys/devices/system/cpu/cpufreq/ondemand/up_threshold ]; then

if [ "`grep ODBATTERY=1 $Config`" ]; then

	busybox echo "95" > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold
	busybox echo "120000" > /sys/devices/system/cpu/cpufreq/ondemand/sampling_rate
  busybox echo "1" > /sys/devices/system/cpu/cpufreq/ondemand/sampling_down_factor
  busybox echo "5" > /sys/devices/system/cpu/cpufreq/ondemand/down_differential
  busybox echo "10" > /sys/devices/system/cpu/cpufreq/ondemand/freq_step

busybox echo "$(date +"%m-%d-%Y %H:%M:%S"): Apllied OnDemand Battery tweak.." >> $DBLog

fi

if [ "`grep ODPERFORMANCE=1 $Config`" ]; then

busybox echo "70" > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold
	busybox echo "50000" > /sys/devices/system/cpu/cpufreq/ondemand/sampling_rate
  busybox echo "2" > /sys/devices/system/cpu/cpufreq/ondemand/sampling_down_factor
  busybox echo "15" > /sys/devices/system/cpu/cpufreq/ondemand/down_differential
  busybox echo "50" > /sys/devices/system/cpu/cpufreq/ondemand/freq_step

busybox echo "$(date +"%m-%d-%Y %H:%M:%S"): Apllied OnDemand Performance tweak.." >> $DBLog

fi


# LulzActive

elif [ -e /sys/devices/system/cpu/cpufreq/lulzactive/inc_cpu_load ]; then

if [ "`grep LBATTERY=1 $Config`" ]; then

	busybox echo "90" > /sys/devices/system/cpu/cpufreq/lulzactive/inc_cpu_load
	busybox echo "1" > /sys/devices/system/cpu/cpufreq/lulzactive/pump_up_step
  busybox echo "2" > /sys/devices/system/cpu/cpufreq/lulzactive/pump_down_step
  busybox echo "50000" > /sys/devices/system/cpu/cpufreq/lulzactive/up_sample_time
  busybox echo "40000" > /sys/devices/system/cpu/cpufreq/lulzactive/down_sample_time
  busybox echo "5" > /sys/devices/system/cpu/cpufreq/lulzactive/screen_off_min_step

busybox echo "$(date +"%m-%d-%Y %H:%M:%S"): Apllied LulzActive Battery tweak.." >> $DBLog

fi

if [ "`grep LPERFORMANCE=1 $Config`" ]; then

	busybox echo "60" > /sys/devices/system/cpu/cpufreq/lulzactive/inc_cpu_load
	busybox echo "4" > /sys/devices/system/cpu/cpufreq/lulzactive/pump_up_step
  busybox echo "1" > /sys/devices/system/cpu/cpufreq/lulzactive/pump_down_step
  busybox echo "10000" > /sys/devices/system/cpu/cpufreq/lulzactive/up_sample_time
  busybox echo "70000" > /sys/devices/system/cpu/cpufreq/lulzactive/down_sample_time
  busybox echo "5" > /sys/devices/system/cpu/cpufreq/lulzactive/screen_off_min_step

busybox echo "$(date +"%m-%d-%Y %H:%M:%S"): Apllied LulzActive Performance tweak.." >> $DBLog

fi

if [ "`grep LBALANCED=1 $Config`" ]; then

	busybox echo "90" > /sys/devices/system/cpu/cpufreq/lulzactive/inc_cpu_load
	busybox echo "4" > /sys/devices/system/cpu/cpufreq/lulzactive/pump_up_step
  busybox echo "1" > /sys/devices/system/cpu/cpufreq/lulzactive/pump_down_step
  busybox echo "10000" > /sys/devices/system/cpu/cpufreq/lulzactive/up_sample_time
  busybox echo "40000" > /sys/devices/system/cpu/cpufreq/lulzactive/down_sample_time
  busybox echo "5" > /sys/devices/system/cpu/cpufreq/lulzactive/screen_off_min_step

busybox echo "$(date +"%m-%d-%Y %H:%M:%S"): Apllied LulzActive Balanced tweak.." >> $DBLog

fi



# SmartassV2

elif [ -e /sys/devices/system/cpu/cpufreq/smartass/max_cpu_load ]; then

if [ "`grep S2BATTERY=1 $Config`" ]; then

	busybox echo "85" > /sys/devices/system/cpu/cpufreq/smartass/max_cpu_load
	busybox echo "70" > /sys/devices/system/cpu/cpufreq/smartass/min_cpu_load
  busybox echo "200000" > /sys/devices/system/cpu/cpufreq/smartass/ramp_up_step
  busybox echo "20000" > /sys/devices/system/cpu/cpufreq/smartass/ramp_down_step
  busybox echo "48000" > /sys/devices/system/cpu/cpufreq/smartass/up_rate_us
  busybox echo "49000" > /sys/devices/system/cpu/cpufreq/smartass/down_rate_us

busybox echo "$(date +"%m-%d-%Y %H:%M:%S"): Apllied SmartassV2 Battery tweak.." >> $DBLog

fi

if [ "`grep S2PERFORMANCE=1 $Config`" ]; then

busybox echo "75" > /sys/devices/system/cpu/cpufreq/smartass/max_cpu_load
	busybox echo "45" > /sys/devices/system/cpu/cpufreq/smartass/min_cpu_load
  busybox echo "0" > /sys/devices/system/cpu/cpufreq/smartass/ramp_up_step
  busybox echo "0" > /sys/devices/system/cpu/cpufreq/smartass/ramp_down_step
  busybox echo "24000" > /sys/devices/system/cpu/cpufreq/smartass/up_rate_us
  busybox echo "99000" > /sys/devices/system/cpu/cpufreq/smartass/down_rate_us

busybox echo "$(date +"%m-%d-%Y %H:%M:%S"): Apllied SmartassV2 Performance tweak.." >> $DBLog

fi


# Conservative

elif [ -e /sys/devices/system/cpu/cpufreq/conservative/up_threshold ]; then

if [ "`grep CBATTERY=1 $Config`" ]; then

	busybox echo "95" > /sys/devices/system/cpu/cpufreq/conservative/up_threshold
	busybox echo "120000" > /sys/devices/system/cpu/cpufreq/conservative/sampling_rate
  busybox echo "1" > /sys/devices/system/cpu/cpufreq/conservative/sampling_down_factor
  busybox echo "4" > /sys/devices/system/cpu/cpufreq/conservative/down_threshold
  busybox echo "10" > /sys/devices/system/cpu/cpufreq/conservative/freq_step

busybox echo "$(date +"%m-%d-%Y %H:%M:%S"): Apllied Conservative Battery tweak.." >> $DBLog

fi

if [ "`grep CPERFORMANCE=1 $Config`" ]; then

busybox echo "60" > /sys/devices/system/cpu/cpufreq/conservative/up_threshold
	busybox echo "40000" > /sys/devices/system/cpu/cpufreq/concervative/sampling_rate
  busybox echo "5" > /sys/devices/system/cpu/cpufreq/conservative/sampling_down_factor
  busybox echo "20" > /sys/devices/system/cpu/cpufreq/conservative/down_threshold
  busybox echo "25" > /sys/devices/system/cpu/cpufreq/conservative/freq_step

busybox echo "$(date +"%m-%d-%Y %H:%M:%S"): Apllied Conservative Performance tweak.." >> $DBLog

fi

# Interactive

elif [ -e /sys/devices/system/cpu/cpufreq/interactive/go_hispeed_load ]; then

if [ "`grep IBATTERY=1 $Config`" ]; then

	busybox echo "95" > /sys/devices/system/cpu/cpufreq/interactive/go_hispeed_load
	busybox echo "10000" > /sys/devices/system/cpu/cpufreq/interactive/min_sample_time
  busybox echo "40000" > /sys/devices/system/cpu/cpufreq/interactive/timer_rate

busybox echo "$(date +"%m-%d-%Y %H:%M:%S"): Apllied Interactive Battery tweak.." >> $DBLog

fi

if [ "`grep IPERFORMANCE=1 $Config`" ]; then

busybox echo "80" > /sys/devices/system/cpu/cpufreq/interactive/go_hispeed_load
	busybox echo "40000" > /sys/devices/system/cpu/cpufreq/interactive/min_sample_time
  busybox echo "20000" > /sys/devices/system/cpu/cpufreq/interactive/timer_rate

busybox echo "$(date +"%m-%d-%Y %H:%M:%S"): Apllied Interactive Performance tweak.." >> $DBLog

fi

# Intellidemand

elif [ -e /sys/devices/system/cpu/cpufreq/interactive/go_hispeed_load ]; then

if [ "`grep IBATTERYPERFORMANCE=1 $Config`" ]; then

	busybox echo "75" > /sys/devices/system/cpu/cpufreq/intellidemand/up_threshold
	busybox echo "0" > /sys/devices/system/cpu/cpufreq/intellidemand/boost_frequency
  busybox echo "50000" > /sys/devices/system/cpu/cpufreq/intellidemand/sampling_rate

busybox echo "$(date +"%m-%d-%Y %H:%M:%S"): Apllied Intellidemand Battery & Performance tweak.." >> $DBLog

fi

fi

exit


else

busybox echo "$(date +"%m-%d-%Y %H:%M:%S"): Your current governor is not supported.." >> $DBLog

fi
