#!/system/bin/sh
# DeadB00st 
# Copyright (C) 2015 deadman0
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your eoption) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#
mount -o remount,rw /
mount -o remount,rw rootfs
mount -o remount,rw /system
busybox mount -o remount,rw /
busybox mount -o remount,rw rootfs
busybox mount -o remount,rw /system

DBLog=/system/etc/DB/Log/DBLogInit.log
if [ "`grep MEDIAONBOOT=1 /system/etc/DB/SwitchesConfig.conf `" ]; then
         busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ): Kill MediaServer on Boot is activated" >> $DBLog
         if [ "`pgrep media`" ]; then
                  busybox killall -9 android.process.media;
                  busybox echo "---Killed android.process.media" >> $DBLog
        else
                  busybox echo "---Can't kill android.process.media" >> $DBLog
                  fi

if [ "`pgrep mediaserver`" ]; then
busybox killall -9 mediaserver;
busybox echo "---Killed MediaServer" >> $DBLog
else
busybox echo "---Can't kill MediaServer" >> $DBLog
fi
else
busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ): Kill MediaServer on Boot is deactivated" >> $DBLog
fi;

