#!/system/bin/sh
# DeadB00st 
# Copyright (C) 2015 deadman0
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your eoption) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#
mount -o remount,rw /
mount -o remount,rw rootfs
mount -o remount,rw /system
busybox mount -o remount,rw /
busybox mount -o remount,rw rootfs
busybox mount -o remount,rw /system

DBLog=/system/etc/DB/Log/DBLogInit.log
Config=/system/etc/DB/SwitchesConfig.conf

if [ "`grep SDTWEAK=1 $Config `" ]; then
         busybox echo "$(date +"%m-%d-%Y %H:%M:%S"): SD Tweak is activated" >> $DBLog

D=1024

MMC=`busybox ls -d /sys/block/mmc* 2>/dev/null`;
for K in $MMC;
do
	if [ -e $K/queue/read_ahead_kb ];
	then
		busybox echo "$D" >  $K/queue/read_ahead_kb;
	fi;
	if [ -e $K/bdi/read_ahead_kb ];
        then
              busybox echo "$D" >  $K/bdi/read_ahead_kb;
        fi;
done

busybox echo "Done!!!"
else 

busybox echo "$(date +"%m-%d-%Y %H:%M:%S"): SD Tweak is deactivated" >> $DBLog

fi
