#!/system/bin/sh
# DeadB00st 
# Copyright (C) 2015 deadman0
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your eoption) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#
mount -o remount,rw /
mount -o remount,rw rootfs
mount -o remount,rw /system
busybox mount -o remount,rw /
busybox mount -o remount,rw rootfs
busybox mount -o remount,rw /system

DBLog=/system/etc/DB/Log/DBLogInit.log
if [ "`grep GAPPSONBOOT=1 /system/etc/DB/SwitchesConfig.conf `" ]; then
         busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ): Kill Gapps on Boot is activated" >> $DBLog
         if [ "`pgrep gms`" ]; then
                  busybox killall -9 com.google.android.gms
                  busybox killall -9 com.google.android.gms.persistent
                  busybox echo "---Killed GMS" >> $DBLog
        else
                  busybox echo "---Can't kill GMS" >> $DBLog
                  fi

if [ "`pgrep gsf`" ]; then
busybox killall -9 com.google.android.gsf
busybox killall -9 com.google.android.gsf.persistent
busybox echo "---Killed GSF" >> $DBLog
else
busybox echo "---Can't kill GSF" >> $DBLog
fi

if [ "`pgrep gapps`" ]; then
busybox killall -9 com.google.process.gapps
busybox echo "---Killed Gapps" >> $DBLog
else
busybox echo "---Can't kill Gapps" >> $DBLog
fi

else
busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ): Kill Gapps on Boot is deactivated" >> $DBLog
fi;
