#!/system/bin/sh
# DeadB00st
# Copyright (C) 2015 deadman0
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#


mount -o remount,rw /
mount -o remount,rw rootfs
mount -o remount,rw /system
busybox mount -o remount,rw /
busybox mount -o remount,rw rootfs
busybox mount -o remount,rw /system
DBLog=/system/etc/DB/Log/DBLog.log
busybox rm -f $DBLog
busybox touch $DBLog
busybox sleep 2
busybox sleep 2
busybox fstrim -v /data
busybox fstrim -v /cache
busybox sleep 1
busybox fstrim -v /system
busybox sleep 1
busybox echo "DeadB00st log:" >> $DBLog
busybox echo "-+-+-+-+-+-+-+-+-" >> $DBLog
busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ): fstrim script is running..." >> $DBLog
busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ): Done!!!" >> $DBLog
busybox sleep 1
