#!/system/bin/sh
# DeadB00st 
# Copyright (C) 2015 deadman0
#=======================================================================#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or (at your eoption) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
#=======================================================================#

mount -o remount,rw /
mount -o remount,rw rootfs
mount -o remount,rw /system
busybox mount -o remount,rw /
busybox mount -o remount,rw rootfs
busybox mount -o remount,rw /system
DBLog=/system/etc/DB/Log/DBLogC.log
busybox rm -f $DBLog
busybox touch $DBLog
busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ): Cleaning..." >> $DBLog
busybox sleep 1
busybox echo "." >> $DBLog
busybox sleep 1
busybox echo "." >> $DBLog
busybox sleep 1
busybox rm -f /data/local/*.apk 2>/dev/null
busybox rm -f /data/local/tmp/*.apk 2>/dev/null
busybox rm -f /data/*.log 2>/dev/null 
busybox rm -f /data/log/*.log 2>/dev/null
busybox rm -f /cache/*.apk 2>/dev/null
busybox rm -f /cache/*.tmp 2>/dev/null 
busybox rm -f /cache/recovery/* 2>/dev/null
busybox rm -f /data/system/dropbox/*.txt 2>/dev/null 
busybox rm -f /data/system/usagestats/* 2>/dev/null 
busybox rm -f /data/backup/pending/*.tmp 2>/dev/null 
busybox rm -f /data/tombstones/* 2>/dev/null 
busybox rm -f /sdcard/LOST.DIR/* 2>/dev/null
busybox rm -f /sdcard/.aptoide/apks/* 2>/dev/null
busybox rm -f /sdcard/.aptoide/icons/* 2>/dev/null
busybox echo "" >> $DBLog
busybox sleep 2
busybox echo "" >> $DBLog
busybox echo "$( date +"%m-%d-%Y %H:%M:%S" ): Cleaned" >> $DBLog
busybox sleep 1
exit
fi

